include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    only_throw_errors: ignore
    unused_shown_name: ignore
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    # Override unrecognized lint rules
    deprecated_consistency: false
    eol_at_end_of_file: false
    library_private_types_in_public_api: false
    noop_primitive_operations: false
    prefer_null_aware_method_calls: false
    require_trailing_commas: false
    use_build_context_synchronously: false
    use_named_constants: false
